### ISSUE TITLE
Style “Actions” in Docs

### ISSUE THREAD

**Issue by mbabker** [BabDev/babdev.com#5]
Make a popout/alert/whatever styled box thing that’s used to style paragraphs that open with `{note}` or `{tip}` or `{deprecated}` and whatnot.  Probably just a simple shadowed box with the different variations having a different colored border, maybe an icon too (assuming my CSS/JS skills can do it).

Once the component is designed, the JavaScript needs to post process these bits.  Maybe the source docs should wrap those in HTML to make it easier than trying to match a paragraph that starts with those placeholders?  (See Laravel docs as an example, they use `<blockquote>` for their callouts but that isn’t semantically correct markup)

**Comment by Sandra97** [comment]
What about
![index](https://user-images.githubusercontent.com/4682328/81824251-8aa38900-9535-11ea-8457-c7bbdd0519f5.png)

**Comment by mbabker** [comment]
That can work

**Comment by Sandra97** [comment]
I would prefer if you manage that. I don't want to break everything, and I don't know which color you want and I know nothing about JS.  

The CSS of my screenshot:

`{
	border-left: 5px solid #ddd;
	padding: 20px 10px;
	font-style: italic;
	color: rgba(0,0,0,.5);
}`
