### ISSUE TITLE
OG / Twitter Image

### ISSUE THREAD

**Issue by Sandra97** [BabDev/babdev.com#6]
What do you think?

![Facebook-Opengraph](https://user-images.githubusercontent.com/4682328/81820910-81182200-9531-11ea-817b-9e0b5c403c9a.png)

(this size should work for Facebook as well as for Twitter)

**Comment by mbabker** [comment]
Sure, if they’re gonna be dumb about things then that seems good enough for all 2 shares this site will ever have 🤣

**Comment by Sandra97** [comment]
It's not because the site won't be shared a lot that it's an enough reason to keep something that doesn't work. The 2 crazy people who will share it will at least have an acceptable display
I'll let you add it to the images folder as I don't have permissions.

**Comment by mbabker** [comment]
Add it to `resources/images`, that folder gets copied over to the right spot when everything is compiled.

**Comment by Sandra97** [comment]
It's what I tried to do this morning
![index](https://user-images.githubusercontent.com/4682328/81933608-f9dcb400-95ed-11ea-9aab-22f5496af939.png)

**Comment by mbabker** [comment]
Do it from your fork.  https://github.com/Sandra97/babdev.com/tree/patch-3/resources/images

**Comment by Sandra97** [comment]
I learned something today
